security:
    providers:
        our_db_provider:
            entity:
                class: App\Entity\Player
                property: email
    encoders:
        App\Entity\Player: bcrypt
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider
            form_login:
                login_path: /login
                check_path: /login
                username_parameter: "login[email]"
                password_parameter: "login[password]"
            logout:
                path: /logout
                target: /
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }